### ISSUE TITLE
编译ckman前端出错

### ISSUE THREAD

**Issue by didiaibiancheng** [housepower/ckman#262]
yarn版本 2.4.0
编译ckman前端执行yarn install时候报错:
```
UnhandledPromiseRejectionWarning: Error: vue-loader-v16@npm:16.2.0: Registry failed to return reference "16.2.0"
18:19:59      at Object.resolve (/home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:231391)
18:19:59      at runMicrotasks (<anonymous>)
18:19:59      at processTicksAndRejections (internal/process/task_queues.js:95:5)
18:19:59      at async n.resolve (/home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:336461)
18:19:59      at async n.resolve (/home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:336461)
18:19:59      at async /home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:356788
18:19:59      at async Module.w (/home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:417407)
18:19:59      at async d (/home/jenkins/agent/workspace/Web/WebArchitecture/ClickHouse-Manager/build/ch-manager/.yarn/releases/yarn-2.4.0.cjs:2:356751)
18:19:59      at async Promise.all (index 48)
```
猜测可能是包版本的原因，尝试删除yarn.lock后编译报错：
```
This dependency was not found:
* vue/src/shared/constants.js in ./src/common/VueComponentBase.ts
To install it, you can run: npm install --save vue/src/shared/constants.js
```
对前端不是很熟，想请问下什么原因呢？

**Comment by CommsayInc** [comment]
遇到了相同的问题. 该如何解决. 项目也不写清楚 node 版本 vue 版本. 全卡在编译这了.
